### ISSUE TITLE
Minor: Typo ColorTranformGenerator

### ISSUE THREAD

**Issue by george-monumental** [subject117/ColorBlindness#1]
n/t

**Comment by hx2A** [comment]
You are correct, I made a typo there. Thanks for point this out. I will fix this and do another release.

**Comment by hx2A** [comment]
I just fixed this and deployed it. All new installations get the new version.

Thanks again for opening an issue.

**Comment by george-monumental** [comment]
Thank you. Also thanks for the excellent documentation of Daltonization! Appreciate it.
